FROM node:20-alpine AS builder
WORKDIR /app
COPY client/package*.json ./
RUN npm install
COPY client/. .
RUN npm run build  # Builds static files to /dist or /build
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html 
COPY nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]